FROM php:8.2.0-fpm

RUN apt-get update && apt-get install -y \
    cron \
    git \
    libzip-dev \
    zip \
    unzip \
    libwebp-dev \
    libjpeg62-turbo-dev \
    libpng-dev \
    libfreetype6-dev \
    libicu-dev \
    libonig-dev \
    libxml2-dev \
    && docker-php-ext-configure gd \
        --with-webp \
        --with-jpeg \
        --with-freetype \
    && docker-php-ext-configure intl \
    && docker-php-ext-install \
        zip \
        bcmath \
        gd \
        mysqli \
        pdo_mysql \
        intl \
    && curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

WORKDIR /var/www/html

COPY cron-file /etc/cron.d/cron-file
COPY run-daemons.sh /run-daemons.sh

ENTRYPOINT ["/bin/bash", "/run-daemons.sh"]
