services:
    php:
        container_name: ${DOCKER_PROJECT_NAME}_php
        restart: unless-stopped
        build: ./docker/php
        volumes:
            - ./:/var/www/html
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini
        depends_on:
            - mysql
        env_file:
            - .env


    nginx-frontend:
        image: nginx:1.19
        container_name: ${DOCKER_PROJECT_NAME}_nginx_frontend
        restart: unless-stopped
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/frontend.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
        ports:
            - "127.0.0.1:${DOCKER_NGINX_PORT}:80"

    nginx-backend:
        image: nginx:1.19
        container_name: ${DOCKER_PROJECT_NAME}_nginx_backend
        restart: unless-stopped
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/backend.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
        ports:
            - "127.0.0.1:${DOCKER_BACKEND_PORT}:80"

    nginx-api:
        image: nginx:1.19
        container_name: ${DOCKER_PROJECT_NAME}_nginx_api
        restart: unless-stopped
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/api.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
        ports:
            - "127.0.0.1:${DOCKER_API_PORT}:80"

    mysql:
        image: mysql:5.7
        container_name: ${DOCKER_PROJECT_NAME}_mysql
        restart: unless-stopped
        environment:
            - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
            - MYSQL_DATABASE=${DOCKER_PROJECT_NAME}
        volumes:
            - ./docker/mysql/db:/var/lib/mysql
        ports:
            - 127.0.0.1:${DOCKER_DATABASE_PORT}:3306

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: unless-stopped
        ports:
            - "127.0.0.1:${PHPMYADMIN_PORT}:80"
        environment:
            PMA_HOST: mysql
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
